### ISSUE TITLE
doesn't start yet

### ISSUE THREAD

**Issue by thaodean** [DeadSix27/python_cross_compile_script#1]
1. The program 'import' can be found in the following packages:
 * imagemagick
 * graphicsmagick-imagemagick-compat
fixed
2 . . ./cross_compiler.py
import: unable to open **X server** `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
from: can't read /var/mail/multiprocessing
from: can't read /var/mail/pathlib
from: can't read /var/mail/urllib.parse
_VERSION: command not found
No command 'class' found, did you mean:
 Command 'iclass' from package 'ivtools-bin' (universe)
 Command 'clasp' from package 'clasp' (universe)
class: command not found
GREEN: command not found
RESET: command not found
YELLOW: command not found
BLUE: command not found
CYAN: command not found
RED: command not found
-su: ./cross_compiler.py: line 36: syntax error near unexpected token `('
-su: ./cross_compiler.py: line 36: `class MissingDependency(Exception):'

**Comment by DeadSix27** [comment]
@mikemyers9 See README:

> As of now it works, however it has no programs defined, later on the defaults will be ffmpeg and mpv.
> Required-packages are also not implemented yet, I highly discourage using this unless you know what you're doing.

EDIT: What exactly did you EDIT and how did you START the program?

EDIT2: Closing this for now, reply if you still need help.
