### ISSUE TITLE
log generated statements to a file (more of a question/request)

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#10]
Hello I didn't readily see in your readme whether the python script has an option  to "log generated linux statements to a file but not run them" ... 
Clarification would be appreciated, Thanks.

**Comment by DeadSix27** [comment]
you can just change
```python
def run_process(self,command,ignoreErrors = False, exitOnError = True):`
````
to 
```python
def run_process(self,command,ignoreErrors = False, exitOnError = True):
	print(command)
	return
```
And it should do what you wan't it to do.

Altho not properly I guess, if you remove the "return" it will show all but keep working. however its not a demo mode then, just a pure debug.

**Comment by hydra3333** [comment]
ok, righty ho. 

that'd suit my purpose, being to see what it actually does under the covers since I am not a linux aware person and need to see actual code with full syntax in order to learn.

**Comment by DeadSix27** [comment]
@hydra3333 that concludes this question I guess.
If you still need help say so and i'll re-open this issue :)!
