### ISSUE TITLE
is it for Linux newbies too ?

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#11]
Ububtu 16.10, blindly followed the readme.

> Packages required, tested on:
> (This list is possibly incomplete and differs from OS to OS)
> Ubuntu 17.04 (Zesty Zapus)
> Ubuntu 16.10 (Yakkety)
> Fedora 25    (Twenty Five)
> global      - texinfo yasm git make automake gcc gcc-c++ pax cvs svn flex bison patch libtoolize nasm hg cmake gettext-autopoint
> mkvtoolnix  - libxslt docbook-util rake docbook-style-xsl
> gnutls      - gperf
> angle       - gyp
> vapoursynth - p7zip
> flac        - docbook-to-man
> youtube-dl  - pando

```
sudo apt-get install -y subversion curl texinfo g++ bison flex cvs yasm automake libtool-bin autoconf gcc cmake git make pkg-config zlib1g-dev mercurial unzip pax wget nasm curl ant
sudo apt-get install -y gcc-c++ libtoolize hg gettext-autopoint libxslt docbook-util rake docbook-style-xsl gperf gyp p7zip docbook-to-man pando 
sudo apt-get install -y build-essential autoconf libtool-bin gettext autopoint gyp gperf autogen pandoc
```
edit: updated apt-get stuff

[sudo] password for u: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gcc-c+
E: Couldn't find any package by regex 'gcc-c+'
E: Unable to locate package libtoolize
E: Unable to locate package hg
E: Unable to locate package gettext-autopoint
E: Unable to locate package libxslt
E: Unable to locate package docbook-util
E: Unable to locate package docbook-style-xsl
E: Unable to locate package pando

```
cd Desktop
./cross_compiler.py -a
[2017-04-18 07:34:53,069][INFO] Building MinGW-w64 in folder 'xcompilers'
[||||||||||||||||||||||||||||||||||||||||||||||||||] - 77.7KiB/77.7KiB (4.1MiB/s)
[2017-04-18 07:34:53,239][ERROR] Previous MinGW build may have failed, delete the compiler folder named 'xcompilers' and try again
```

**Comment by DeadSix27** [comment]
@hydra3333 
Its not for linux beginners no.
open build.log in xcompilers and see why it failed.
Also install:
sudo apt install build-essential autoconf libtool-bin gettext
And for the others, google is your friend, It isn't that hard to find out, e.g if you just run "hg" in ubuntu it will either work or complain and usually show you in which package hg can be found and that you'll just install.

EDIT: The packages is the only thing I have not yet worked on.
Beside that it should work, at least on ubuntu 16.10,17.04 and fedora25.

**Comment by hydra3333** [comment]
:) so far, re-running a couple of times,

```
sudo apt-get install -y subversion curl texinfo g++ bison flex cvs yasm automake libtool-bin autoconf gcc cmake git make pkg-config zlib1g-dev mercurial unzip pax wget nasm curl ant
sudo apt-get install -y gcc-c++ libtoolize hg gettext-autopoint libxslt docbook-util rake docbook-style-xsl gperf gyp p7zip docbook-to-man pando 
sudo apt-get install -y build-essential autoconf libtool-bin gettext autopoint gyp gperf autogen pandoc
```

**Comment by DeadSix27** [comment]
@hydra3333 feel free to add the missing packages to the list and Pull-request it it will help others.

**Comment by hydra3333** [comment]
ok.

**Comment by hydra3333** [comment]
updating the post above as I go ... ubuntu 16.10 in a VM

**Comment by DeadSix27** [comment]
@hydra3333 I can also close this i guess.

**Comment by hydra3333** [comment]
Sure, why not, I can still add to this  even if it's closed.
https://github.com/DeadSix27/python_cross_compile_script/issues/11#issuecomment-295221204

**Comment by DeadSix27** [comment]
@hydra3333 what i mean't is, the question was answered and you seem to be in the other thread anyway :)

**Comment by hydra3333** [comment]
OK by me, Sir or Madam.
