### ISSUE TITLE
add avisynthplus_headers (ffmpeg building was broken)

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#115]
Hello.
ffmpeg no longer builds due to recent commits to remove avisynth and replace it with avsynthplus.

I popped this `	'avisynthplus_headers',` into ffmpeg_depends.py
and created `avisynthplus_headers.py` as a dependency per info in the ffmpeg commits
```
{
	'repo_type' : 'git',
	#'depth_git' : 0,
	#'branch' : '',											
	'url' : 'https://github.com/AviSynth/AviSynthPlus',
	'recursive_git' : True,
	'source_subfolder' : 'avisynth-build',
	'conf_system' : 'cmake',
	'configure_options' : '.. {cmake_prefix_options} -DCMAKE_INSTALL_PREFIX={target_prefix} -DHEADERS_ONLY:bool=on ',
	'_info' : { 'version' : 'git (master)', 'fancy_name' : 'AviSynthPlus headers' },
}
```
Hope it builds now ;)

**Comment by hydra3333** [comment]
people must be staying home from the covid19 thing and getting stuck into commits on a range of things !

**Comment by DeadSix27** [comment]
https://github.com/DeadSix27/python_cross_compile_script/commit/32afc4ad1d856507422ffd3cc00db063a7f4b7b0
