### ISSUE TITLE
Add Polly/Hunter, MLAlchemy, others

### ISSUE THREAD

**Issue by roscopecoltran** [DeadSix27/python_cross_compile_script#13]
Hi,

I will look at your script tomorrow but here are a couple of suggestions to make it more flexible.

**Script for nested commands/sub-commands**
https://github.com/marekjm/clap/blob/devel/examples/nested.json
https://github.com/datagrok/subcommander
https://github.com/hyde/commando

**Script verbs:**
https://github.com/floooh/fips/tree/master/verbs

**project/package macros per platform/toolchains to store into yaml/json file**
https://pypi.python.org/pypi/mlalchemy

**CMake Package Managers (with CMake Config Mode !):**
https://github.com/ruslo/hunter

**CMake Toolchains:**
https://github.com/ruslo/polly (Simple but useful !)
https://github.com/floooh/fips/tree/master/configs

**CMake Modification/Patches:**
https://github.com/polysquare/cmake-ast/tree/master/cmakeast (find_package,... etc with column and line)
https://github.com/chrisvm/pymake/blob/master/pymake/cmake_list.py

Cheers,
Richard

**Comment by DeadSix27** [comment]
@roscopecoltran some of these seem useful indeed, especially the "nested commands/sub-commands" stuff but I try to not use any extra python library, so I'll stick to things that I can easily add to the main script file and not have a seperate file or require a lib to be installed.

Stuff that can be simply added to the existing file is fine tho.

I don't quite understand the rest tho, I'll have to read further into them tomorrow, but isn't polly just a script that builds a toolchain, like the mingw script I use? In which case, that seems rather bloated no? Considering I only need the mingw-64 toolchain, no other as I do not plan to support any other OS than Win64.
