### ISSUE TITLE
exe compiled successfully, but...

### ISSUE THREAD

**Issue by rzcat** [DeadSix27/python_cross_compile_script#17]
curl.exe and ffmpeg.exe, both work fine on Win10, but show "exe has stopped working" on 2008 r2.
---
Fedora 25 x86_64, used rdp's script before, got the final exe, runs fine on almost my every windows machine. Days ago I decided to take a shot with your script, to get ffmpeg with newer GCC, and with libx265 multi-bit. With ffmpeg.exe compiled successfully before, I have to install several other packages before running your script:
`dnf install gettext-devel gperf autogen`
gettext-devel is for gettext-autopoint, libtool is for libtoolize, and I have to force an update to nasm, then I ran 
`./cross_compiler.py -pl wget,curl,ffmpeg_static_non_free_opencl`
the first wget got some error involving some sort of url.so, I couldn't remember clearly, and I just ignored it jumping to curl and ffmpeg.
They got compiled fine, except ffmpeg has some updated componets which you have to edit manually. To download freetype I have to use sourceforge instead as I coundnt connect to the original server in the script. I got exe at last, curl.exe and ffmpeg.exe, both work fine on Win10, but:
```
curl.exe shows "exe has stopped working" on 2008 r2
ffmpeg.exe shows "The computer is missing OpenCL.dll" some sort of things
```
Google tells me that Windows Server 2008 r2 got some problems of OpenCL, so I went to execute
`./cross_compiler.py -p ffmpeg_static`
and got another ffmpeg.exe, smaller. This time, ffmpeg.exe shows "exe has stopped working" on 2008 r2, while still works fine on Win10. Currently I dont have another 64bit machine running another Windows OS, so I couldnt test more. But the ffmpeg.exe I got from rdp's script does run fine on this 2008 r2.
If you wouldnt mind, please take a look, thanks.

**Comment by DeadSix27** [comment]
@rzcat OpenCL is not built by default and I can't support it much, as I have no clue how that works with multiple GPU brands etc, I assume you lack openCL drivers from your manufacturer
And about the crash of curl, you have to adjust march to your CPU arch, if you do not have a cpu with at least Sandybridge it will not work by default, set that to something older in the top of the file and I'm unsure how old WindowsXP is, was it around 2008? if so, maybe server2008 is way too old too and would require "XP Support" in some apps, which I do not plan on adding. 

Try changing the march, see URL next to it in the comments then find newest gpu drivers (and if the server has no proper dedicated gpu, then don't build opencl.)

**Comment by rzcat** [comment]
@DeadSix27
thanks for quick response, using
`_ORIG_CFLAGS       = '-O3'` on line 68
without minimum spu arch option, got an exe that runs on my old 2008 r2 successfully

**Comment by DeadSix27** [comment]
All working fine now I assume. You could also try finding out the cpu architecture you use, e.g pentium4, core2, etc, find them in this list: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

Then set -march= to that name and try with that, can increase performance, which is why I use that in the first place., _altho i should probably make cflags also set cxxflags..._.. _another time_

**Comment by rzcat** [comment]
@DeadSix27 
I did a few more tests and build a skylake ffmpeg for my new machine. It went successfully. However after I copied out the exe, I modified the script erasing the march options and re-run the script, it just told me everything is up-to-date and all builds are already done.
Can this -march option be made into every little program? I mean just like you said you can even add your own programs to the script by adding sections.
It's kind of a feature request, running
``./script.sh -pl ffmpeg_haswell,ffmpeg_skylake,ffmpeg_none``
will get you three ffmpeg.exe with different minimum cpu arch

**Comment by DeadSix27** [comment]
Sure, you can just copy that and do another for haswell, too (see below for example):
But, tbh, I'd just use haswell, on both platforms, looking @the instructions sets, not much got added since haswell, FMA2 maybe, but the most important programs (x264/65 etc) all dynamically use those features and I'd guess there will not be a big impact on performance (if any) if you keep using haswell.

What I originally meant is, using any recent march vs using none at all, which imo one shouldn't. 
But since you can use haswell on both.. its good enough.

```
	'ffmpeg_static_skylake' : {
		'repo_type' : 'git',
		'url' : 'git://git.ffmpeg.org/ffmpeg.git',
		'rename_folder' : 'ffmpeg_static_skylake',
		'configure_options': '!VAR(ffmpeg_base_config)VAR! --enable-libbluray --prefix={product_prefix}/ffmpeg_static_git.installed --disable-shared --enable-static',
		'depends_on': [ 'ffmpeg_depends' ],
		'env_exports' : {
			'CFLAGS'   : '-march=skylake',
			'CXXFLAGS' : '-march=skylake',
		},
		'_disabled' : True, # we disable this, so it does not show up in listing.
	},
```
