### ISSUE TITLE
"--enable-netcdf" not recognised

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#19]
"--enable-netcdf" is no longer listed as an ffmpeg commandline option
replaced by libmysofa ?

**Comment by DeadSix27** [comment]
Fixed in https://github.com/DeadSix27/python_cross_compile_script/commit/a04c8e56b7df01d18c319a52e8d2f104855d5fac

**Comment by hydra3333** [comment]
thank you.
