### ISSUE TITLE
? SLD2 and ./autogen.sh -fiv 

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#22]
Just checking in, built sdl2 from git by hand and it complained and needed 
`./autogen.sh -fiv `
before the configure would work properly.  
Not sure how it goes with the .py here as I haven't run that today.

**Comment by DeadSix27** [comment]
@hydra3333 script automatically does that when needed: https://github.com/DeadSix27/python_cross_compile_script/blob/master/cross_compiler.py#L1225

To be sure I let it build a fresh SDL2 copy and it worked fine.
