### ISSUE TITLE
libbluray patch for git version not working ?

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#25]
Does this patch still work for you ?  
After download from git, checking for contrib/libudfread the folder exists but is empty and there's no file udfread.c to be found anywhere in that tree :(

`https://raw.githubusercontent.com/DeadSix27/python_cross_compile_script/master/patches/libbluray_git_remove_strtok_s.patch`

**Comment by hydra3333** [comment]
hmm, looking in here https://git.videolan.org/ I noticed this in the page ... do we now have to download/build it separately ?

> libudfread.git | UDF reader |   | 2 weeks ago | summary | shortlog | log | tree

**Comment by hydra3333** [comment]
newbie alert, you get an error 

> 500 - Unknown type of object 

when you try to click on history in libudfread here

> drwxr-xr-x |   | .. |  
> drwxr-xr-x | - | asm | tree | history
> m--------- | - | libudfread | history

from this link
https://git.videolan.org/?p=libbluray.git;a=tree;f=contrib;h=24bdd6d8020f78ac5fa07549088725763fb22880;hb=HEAD

**Comment by DeadSix27** [comment]
@hydra3333 udf is a submodule in the libbluray git repo.. should be download initially. 

EDIT2: here: https://git.videolan.org/?p=libbluray.git;a=blob;f=.gitmodules;h=e2722d7f447a39fccb97ba891b1c908940a204be;hb=HEAD

See in that file, udf is a submodule, my script should automatically download it.. try removing the libbluray_git folder and just re-run it, if something doesn't work just always do that. usually fixes most problems.
