### ISSUE TITLE
Broken mingw-w64 branch

### ISSUE THREAD

**Issue by epilsits** [DeadSix27/python_cross_compile_script#36]
~Looks like mingw-w64 broke their repo somehow?~ Getting a "reference is not a tree" error during build when trying to checkout commit 3f31320b2b37a4bf4d0c973a60d43fcb309514a1. Using latest commit 409500c17cc7a5e10ad3e305dfeda4a3c941853b works for now.

**Comment by epilsits** [comment]
Ah, it's because of cloning with --depth=1. So, either do full clone, or don't specify a commit to checkout maybe?

**Comment by hydra3333** [comment]
thank you

**Comment by DeadSix27** [comment]
@hydra3333 @epilsits that commit worked fine for me, even wit depth1, see if the new commit i changed it to, fixes it for you, otherwise there might be another issue.. is your git up to date?

**Comment by epilsits** [comment]
The reason for failure on new build, was depth=1 only pulls the last commit history. So you can't checkout any older branches. At the time of my build, 409500 was committed, so checkout of 3f3132 failed. There's no good solution to this if you want to keep using the depth setting. As soon as their git has another commit, then checkout of 490500 will fail too.

Perhaps your local repo already had the history. I started clean.

**Comment by DeadSix27** [comment]
@epilsits Oh derp on my end.. i forgot that git clone has the "--branch" option and coded it once to "clone a specific repo with this commit" to then realize.. nvm it can only clone specific branches not specific commits.. reverted the code but then forgot about it.. so ye let me disable shallow then..

There is this approach: https://stackoverflow.com/questions/31278902/how-to-shallow-clone-a-specific-commit-with-depth-1
But meh..
