### ISSUE TITLE
zvbi patching fails, 'git apply' does not allow patch fuzzing like 'patch'

### ISSUE THREAD

**Issue by epilsits** [DeadSix27/python_cross_compile_script#39]
Imperfect patches, such as those for zvbi, fail with 'git apply'. Perhaps allow a fallback to 'patch', or remake the zvbi patches to fix the offsets.

**Comment by epilsits** [comment]
Build is still failing. I'm not getting errors from the patch, but it is not being applied. If I run it manually with verbose, here's the output.
```
$ git apply -v -p1 < 0001-zvbi-0.2.35_win32.patch
Skipped patch 'configure.in'.
Skipped patch 'src/conv.c'.
Skipped patch 'src/export.c'.
Skipped patch 'src/io.c'.
Skipped patch 'src/packet.c'.
Skipped patch 'src/proxy-msg.c'.
Skipped patch 'src/proxy-msg.h'.
Skipped patch 'src/vbi.c'.
Skipped patch 'zvbi-0.2.pc.in'.
```

git apply seems really pissy about applying patches. Same command with 'patch' works ok.

**Comment by DeadSix27** [comment]
Can't reproduce though,


```
$ git --version
git version 2.16.1
$ rm -r workdir/x86_64/zvbi-0.2.35/
$ ./cross_compiler.py -gd zvbi
............
[20:37:26][INFO] Downloading patch 'https://raw.githubusercontent.com/DeadSix27/python_cross_compile_script/master/patches/zvbi/0001-zvbi-0.2.35_win32.patch' to: 0001-zvbi-0.2.35_win32.patch
[20:37:26][INFO] Requesting : https://raw.githubusercontent.com/DeadSix27/python_cross_compile_script/master/patches/zvbi/0001-zvbi-0.2.35_win32.patch - 1.9KiB
Downloading: 0001-zvbi-0.2.35_win32.pa 100% [████████████████████████████████████████]   1.9 KiB/  1.9 KiB |531.2 KiB/s | Time: 0:00:00
[20:37:26][INFO] Patching source using: '0001-zvbi-0.2.35_win32.patch'
[20:37:26][DEBUG] Running 'git apply -p1 < "0001-zvbi-0.2.35_win32.patch"' in '/xc/gcc7/workdir/x86_64/zvbi-0.2.35'
[20:37:26][INFO] Downloading patch 'https://raw.githubusercontent.com/DeadSix27/python_cross_compile_script/master/patches/zvbi/0002-zvbi-0.2.35_ioctl.patch' to: 0002-zvbi-0.2.35_ioctl.patch
[20:37:26][INFO] Requesting : https://raw.githubusercontent.com/DeadSix27/python_cross_compile_script/master/patches/zvbi/0002-zvbi-0.2.35_ioctl.patch - 440.0B
Downloading: 0002-zvbi-0.2.35_ioctl.pa 100% [████████████████████████████████████████████] 440.0 B/440.0 B |130.4 KiB/s | Time: 0:00:00
[20:37:26][INFO] Patching source using: '0002-zvbi-0.2.35_ioctl.patch'
[20:37:26][DEBUG] Running 'git apply -p1 < "0002-zvbi-0.2.35_ioctl.patch"' in '/xc/gcc7/workdir/x86_64/zvbi-0.2.35'
[20:37:26][INFO] Configuring 'zvbi' with: --host=x86_64-w64-mingw32 --prefix=/xc/gcc7/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --disable-shared --enable-static --disable-dvb --disable-bktr --disable-nls --disable-proxy --without-doxygen
[20:37:26][DEBUG] Running './configure --host=x86_64-w64-mingw32 --prefix=/xc/gcc7/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --disable-shared --enable-static --disable-dvb --disable-bktr --disable-nls --disable-proxy --without-doxygen' in '/xc/gcc7/workdir/x86_64/zvbi-0.2.35'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
.............
```

EDIT: unless it doesnt apply, one sec.

**Comment by epilsits** [comment]
There's no error during patching. It errors on the build because the patch was not applied. Cannot find 'langinfo.h' IIRC.

If you manually apply the patch with verbose logging, does it work for you? If so, is git apply picky about local commits or something? I'm running this on my fork, so the commits are different.

**Comment by DeadSix27** [comment]
Ye i just realized i run git apply non verbose... but still it applies on my end:

```
[20:42:37][INFO] Patching source using: '0001-zvbi-0.2.35_win32.patch'
Checking patch configure.in...
Checking patch src/conv.c...
Checking patch src/export.c...
Checking patch src/io.c...
Checking patch src/packet.c...
Checking patch src/proxy-msg.c...
Checking patch src/proxy-msg.h...
Checking patch src/vbi.c...
Checking patch zvbi-0.2.pc.in...
Applied patch configure.in cleanly.
Applied patch src/conv.c cleanly.
Applied patch src/export.c cleanly.
Applied patch src/io.c cleanly.
Applied patch src/packet.c cleanly.
Applied patch src/proxy-msg.c cleanly.
Applied patch src/proxy-msg.h cleanly.
Applied patch src/vbi.c cleanly.
Applied patch zvbi-0.2.pc.in cleanly.
```

**Comment by epilsits** [comment]
Something is weird on my end then. I'm getting 'skipped patch' for both patch sets.
```
[19:46:03][DEBUG] Running 'git apply -v -p1 < "0001-zvbi-0.2.35_win32.patch"' in '/data/python_cross_compile_script/workdir/x86_64/zvbi-0.
2.35'
Skipped patch 'configure.in'.
Skipped patch 'src/conv.c'.
Skipped patch 'src/export.c'.
Skipped patch 'src/io.c'.
Skipped patch 'src/packet.c'.
Skipped patch 'src/proxy-msg.c'.
Skipped patch 'src/proxy-msg.h'.
Skipped patch 'src/vbi.c'.
Skipped patch 'zvbi-0.2.pc.in'.

[19:46:03][DEBUG] Running 'git apply -v -p1 < "0002-zvbi-0.2.35_ioctl.patch"' in '/data/python_cross_compile_script/workdir/x86_64/zvbi-0.
2.35'
Skipped patch 'contrib/ntsc-cc.c'.
```

**Comment by DeadSix27** [comment]
You are deleting the old zvbi folder each time you test, right? And your git is up to date right? Are permissions ok?

**Comment by epilsits** [comment]
Yes, complete rm -rf of the zvbi folder. Permissions are ok, other patches seem to work, and 'patch' command works OK. Latest system git, 2.14.1. Ubuntu 17.10.

**Comment by DeadSix27** [comment]
Maybe something between the versions changed this behavior?

**Comment by epilsits** [comment]
I'm not sure :/ I assume that means you're running 2.16.1? I'll have to see if there's a way to update to that version and test.

**Comment by DeadSix27** [comment]
@epilsits Yes, 2.16.1, for now just replace git apply with patch in your local copy until you/we/I figure out why it won't work with git apply.

**Comment by epilsits** [comment]
Upgraded to 2.16.1, same result. 'verbose' is not very verbose :/

**Comment by DeadSix27** [comment]
@epilsits I can't think of any other reason than permissions or something like that.

If you completely manually download&extract zvbi and git-apply the patches, does it also not work?

Maybe its the extraction causing the mess up

**Comment by epilsits** [comment]
Correct, complete manual process fails too. wget to download, manually copy in patch file, run 'git apply -v', get skipped messages. Then run with 'patch' instead, success. The only difference I can see, is my local repo is my fork with the extra commits.

**Comment by DeadSix27** [comment]
Try running git apply with -v and --unsafe-paths

**Comment by DeadSix27** [comment]
@epilsits See:
`By default, a patch that affects outside the working area (either a Git controlled working tree, or the current working directory when "git apply" is used as a replacement of GNU patch) is rejected as a mistake (or a mischief).
When git apply is used as a "better GNU patch", the user can pass the --unsafe-paths option to override this safety check. This option has no effect when --index or --cached is in use.`

**Comment by epilsits** [comment]
```
[20:13:59][DEBUG] Running 'git apply -v --unsafe-paths -p1 < "0001-zvbi-0.2.35_win32.patch"' in '/data/python_cross_compile_script/workdir
/x86_64/zvbi-0.2.35'
Skipped patch 'configure.in'.
Skipped patch 'src/conv.c'.
```

**Comment by DeadSix27** [comment]
I was really hoping that would be the solution...

try `--allow-binary-replacement` totally unrelated.. definitely wont fix this and the patch doesn't even do any binary replacement, but still try it.
Also try --3way, but at this point I'm just going through all the arguments..

**Comment by epilsits** [comment]
No luck.

**Comment by DeadSix27** [comment]
No idea then.. try on a clean VM with both git versions? Or in a different folder, like somewhere in the home directory?

**Comment by epilsits** [comment]
It's broken when it's inside your git repo folder structure. If I move the zvbi folder outsize the repo, the patch applies cleanly. But if it's anywhere underneath, it breaks.

Is your test env a git clone, or just a download? I didn't even have to build anything special to repro.

```
cd ~
mkdir tmp
cd tmp
git clone https://github.com/DeadSix27/python_cross_compile_script
cd python_cross_compile_script
mkdir workdir
cd workdir
wget zvbi
tar -xf zvbi
cd zvbi
wget patch
git apply
```

**Comment by DeadSix27** [comment]
@epilsits Ok now i get it.... you cloned my repo.. I didn't, so logically i don't get that issue...

My test env is literally just the python file, nothing else is previously in the root folder.

**Comment by DeadSix27** [comment]
Guess i have to delete the .git folder upon start..

**Comment by epilsits** [comment]
Ouch.. maybe rename during runtime instead?

**Comment by epilsits** [comment]
More importantly though, I don't like the idea of 'git apply' skipping patches and not raising errors. Any functional reason to use 'git apply' instead of 'patch'?

**Comment by DeadSix27** [comment]
git apply is better @ handling fuzz and i think i encountered 1 patch which never worked with gnu-patch but worked fine with git-apply, although I can't remember of the top of my head, a solution can be having the ability to select patch and git apply, or a fall back.

**Comment by DeadSix27** [comment]
@epilsits Right, I remember, binary patches.. GNU Patch has no support for those.

**Comment by epilsits** [comment]
It's easy enough to maintain my repo elsewhere, that's no big deal. But if it's possible to have git apply raise errors and stop, rather than continue, that would be a good change.

**Comment by DeadSix27** [comment]
@epilsits It raises errors only when it encounters one, the issue is that it won't work properly due to .git folder existing, probably have to delete that, I don't see any reason why you would clone the repo anyway, the main .py file is the only requirement.
