### ISSUE TITLE
Typo in run_process for 'make clean', wrong arg to -j

### ISSUE THREAD

**Issue by epilsits** [DeadSix27/python_cross_compile_script#40]
Typo here, line 1608
`self.run_process('{0} clean -j {0}'.format( mkCmd, _CPU_COUNT ),True)`

Should probably be
`self.run_process('{0} clean -j {1}'.format( mkCmd, _CPU_COUNT ),True)`

**Comment by DeadSix27** [comment]
@epilsits for something that small you should prob pm me on discord/IRC or just PR it.
