### ISSUE TITLE
query - ffmpeg removal of NV/CUDA headers

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#43]
Seeking advice ... (asking the same thing over at rdp's site)

this patch seems to be removing headers to do with NV stuff https://patchwork.ffmpeg.org/patch/7735/

I wonder, like jb here jb-alvarado/media-autobuild_suite@42df66a#commitcomment-27827282 does this now need to be "installed" before one can build ffmpeg with the NV/CUDA encoder stuff baked into ffmpeg ?

**Comment by DeadSix27** [comment]
@hydra3333 has to be installed now: https://github.com/DeadSix27/python_cross_compile_script/commit/3dd2de00545d84aa711b5df133b07b55e7bbeca5#diff-e223906984ace16458e9ef6f3437aeeeR3420

Just read the commit message here `https://github.com/FFmpeg/FFmpeg/commit/27cbbbb33f259de7c795d2b75edf7b240f0f82e6`

**Comment by hydra3333** [comment]
Thank you yes.
