### ISSUE TITLE
x265 [error]: Only bit depths of 0 are supported in this build

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#46]
Hello.  Just built a fresh multibit x265 using your wonderful python script, however I receive an unusual error when using it.  This commandline 

`".\ffmpeg.exe" -hide_banner -v verbose  -threads 0 -i ".\ABC HD interlaced.aac.mp4" -t 15 -threads 0 -an  -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0" -pixel_format yuv420p -pix_fmt yuv420p -strict -1 -f yuv4mpegpipe - 2> .\zzz1.x265.txt | ".\x265.exe" --log-level full --input-depth 8 --input - --preset fast --crf 25 --output-depth 8 --output ".\zzz.h265" 1> .\zzz2.x265.txt 2>&1`

yields the error 
> `x265 [error]: Only bit depths of 0 are supported in this build`

whereas  these work OK (rdp based ffmpeg builds):

`".\ffmpeg.exe" -hide_banner -v verbose  -threads 0 -i ".\ABC HD interlaced.aac.mp4" -t 15 -threads 0 -an  -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0" -pixel_format yuv420p -pix_fmt yuv420p -strict -1 -f yuv4mpegpipe - 2> .\zzz1.txt | ".\ffmpeg.exe" -strict -1 -hide_banner -v verbose  -threads 0 -i - -c:v libx264 -crf 23 -an  -y .\zzz.mp4 2> .\zzz2.txt `

`".\ffmpeg.exe" -hide_banner -v verbose -threads 0 -i ".\ABC HD interlaced.aac.mp4" -t 15 -threads 0 -an  -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -flags +ildct+ilme -top 1 -pixel_format yuv420p -pix_fmt yuv420p -strict -1 -f yuv4mpegpipe - 2> .\zzz1-i.txt | ".\ffmpeg.exe" -hide_banner -v verbose -threads 0 -strict -1 -i - -c:v libx264 -flags +ildct+ilme -top 1 -crf 23 -an  -y .\zzz-i.mp4 2> .\zzz2-i.txt`

Advice would be welcomed ... is x265 building properly ?

**Comment by hydra3333** [comment]
On the off chance it required 10bit input, I also tried this but received the same error

`".\ffmpeg_10bit.exe" -hide_banner -v verbose  -threads 0 -i ".\ABC HD interlaced.aac.mp4" -t 15 -threads 0 -an  -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0" -pixel_format yuv420p10le -pix_fmt yuv420p10le -strict -1 -f yuv4mpegpipe - 2> .\zzz1.x265a.txt | ".\x265.exe" --log-level full --input-depth 10 --input - --preset fast --crf 25 --output-depth 10 --output ".\zzza.h265" 1> .\zzz2.x265a.txt 2>&1`

**Comment by hydra3333** [comment]
And, well, it was worth building a 10-bit only x265 and trying that ...

`".\ffmpeg_10bit.exe" -hide_banner -v verbose  -threads 0 -i ".\ABC HD interlaced.aac.mp4" -t 15 -threads 0 -an  -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0" -pixel_format yuv420p10le -pix_fmt yuv420p10le -strict -1 -f yuv4mpegpipe - 2> .\zzz1.x265a.txt | ".\x265_10bit.exe" --log-level full --input-depth 10 --input - --preset fast --crf 25 --output-depth 10 --output ".\zzzb.h265" 1> .\zzz2.x265b.txt 2>&1`

However the same error was provided.

**Comment by hydra3333** [comment]
Interestingly, zeranoe has a message here https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=2&t=5475

So ... I tried that ffmpeg multi-bit build and it works for both 8bit and 10bit.

Zeranoe must do something a bit different in building and linking to the x265 libraries I guess.

`".\ffmpeg_zeranoe.exe" -hide_banner -v verbose  -threads 0 -i ".\ABC HD interlaced.aac.mp4" -t 15 -threads 0 -an  -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0" -pixel_format yuv420p -pix_fmt yuv420p -strict -1 -f yuv4mpegpipe - 2> .\zzz1.h265.zeranoe_8bit.txt | ".\ffmpeg_zeranoe.exe" -strict -1 -hide_banner -v verbose  -threads 0 -i - -strict -1 -c:v:0 libx265 -crf 28 output.mp4 -an  -y .\zzz.h265.zeranoe_8bit.mp4 2> .\zzz2.h265.zeranoe_8bit.txt `

`".\ffmpeg_zeranoe.exe" -hide_banner -v verbose  -threads 0 -i ".\ABC HD interlaced.aac.mp4" -t 15 -threads 0 -an  -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0" -pixel_format yuv420p10le -pix_fmt yuv420p10le -strict -1 -f yuv4mpegpipe - 2> .\zzz1.h265.zeranoe_10bit.txt | ".\ffmpeg_zeranoe.exe" -strict -1 -hide_banner -v verbose  -threads 0 -i - -pixel_format yuv420p10le -pix_fmt yuv420p10le -strict -1 -c:v libx265 -crf 28 output.mp4 -an  -y .\zzz.h265.zeranoe_10bit.mp4 2> .\zzz2.h265.zeranoe_10bit.txt `

Although the 10-bit piping worked, the receiving ffmpeg then auto-scaled it back to yuv420p when encoding.

Now, if only Zeranoe built with OpenCL as well !

Would there be any chance of you finding out how Zeranoe did it and replicating that ?

**Comment by DeadSix27** [comment]
idk about the ffmpeg thing, what worries me is x265 having no version apparently, has it always had that? See:
```
D:\binaries>x265.exe --version
x265 [info]: HEVC encoder version (null)
x265 [info]: build info (null)
```

Pretty sure it had a version before... I can't figure out what changed, nothing in the code since reverting to a commit months ago didn't make a difference..

**Comment by DeadSix27** [comment]
There should be one though:
`cd /xc/gcc7/workdir/x86_64_products/x265_multibit/source/_build/common && /xc/gcc7/workdir/toolchain/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-g++ .... -DX265_VERSION=2.6+24-69cfe46e8a3b -DLINKED_10BIT=1 -DLINKED_12BIT=1 -DENABLE_ASSEMBLY=1  ... version.cpp`

**Comment by DeadSix27** [comment]
Well I reported it here, as I can't figure it out myself:
https://bitbucket.org/multicoreware/x265/issues/392/version-is-null-issue-with-cross-compiling

**Comment by hydra3333** [comment]
> idk about the ffmpeg thing, what worries me is x265 having no version apparently, has it always had that? 

I did notice that and thought it unusual too, but have only started to look at h.265 recently and so didn't have anything to compare it to.

**Comment by hydra3333** [comment]
Oh dear.   I came across this by accident:
https://github.com/Zeranoe/mingw-w64-build/commit/7c8df9bb250b6498a7738d3f3609a0b62ad2f798

```
Revert Binutils to 2.29.1

2.30 seems have have an issue with x265:
Stream #0:0 -> #0:x265 [error]: Only bit depths of 0 are supported in this build

Further investigation is needed to find the real issue here.
```

**Comment by DeadSix27** [comment]
why did that surface just now though? I can't remember seeing this issue a few days ago and I'm sure I used x265 in that time, strange. But thanks for finding that out, Ill add it to the ticket @ x265 and revert it on my end too (in a bit)

**Comment by DeadSix27** [comment]
fixed in https://github.com/DeadSix27/python_cross_compile_script/commit/896f4dc95e4eb27b12308b3eb63560983f177bd0
