### ISSUE TITLE
not an issue, just a comment - really nice work

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#49]
Well, I'm impressed by your work !

I also do an rdp-based roll my own ffmpeg x64 build (mainly for ongoing learning purposes) - and with identical ffmpeg commandlines your hevc_nvenc consistently achieves **_twice_** the throughput that mine does.  Nice work.

`-hide_banner -v verbose -strict -1 -init_hw_device opencl=ocl:1.0 -filter_hw_device ocl -threads 0 -i ".\test.mp4" -t 300 -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0" -pix_fmt yuv420p -c:v hevc_nvenc -profile:v main -level 5.1 -preset slow -rc vbr_hq -cq 28 -rc-lookahead 32 -spatial_aq 1 -c:a libfdk_aac -cutoff 18000 -ab 384k -ar 48000 -movflags +faststart -y ".\converted_test.h265.mp4" 
`
your build
`frame= 7500 fps=209 q=29.0 Lsize=   86620kB time=00:05:00.02 bitrate=2365.2kbits/s speed=8.38x `

my build
`frame= 7500 fps=120 q=29.0 Lsize=   86620kB time=00:05:00.02 bitrate=2365.2kbits/s speed=4.81x`

**Comment by hydra3333** [comment]
yah, tried a few more tests and for some reasons your ffmpeg build is consistently circa twice as fast as a variant of an rdp script based build, for OpenCL transcoding.  The resulting .mp4 files are bit identical, just a LOT faster.

eg 576p
`frame= 7500 fps=392 q=23.0 Lsize=   47433kB time=00:05:00.02 bitrate=1295.1kbits/s speed=15.7x   `
vs
`frame= 7500 fps=145 q=23.0 Lsize=   47433kB time=00:05:00.02 bitrate=1295.1kbits/s speed=5.79x     `

and for a 1080i25 yadif'd to p25
`frame= 7500 fps=206 q=29.0 Lsize=   86620kB time=00:05:00.02 bitrate=2365.2kbits/s speed=8.26x    `
vs
`frame= 7500 fps=119 q=29.0 Lsize=   86620kB time=00:05:00.02 bitrate=2365.2kbits/s speed=4.76x    `

Out of interest I tried yours with the latest NASM instead of yasm -  The resulting .mp4 files were again bit identical, virtually no difference in fps.

**Comment by DeadSix27** [comment]
@hydra3333 might be the cflags, I build with O3 and I use winpthreads, idk what rdp uses..

**Comment by hydra3333** [comment]
I used O3 as well, it may be the pthreads.
Anyway, liking your work so have migrated to that now.
Thank you.
