### ISSUE TITLE
x264 build needs extra dependencies for more flexible input/output formats

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#57]
I notice that the x264 build isn't built with
(a) lavf input formats
(b) mp4 output format
```
x264.exe --help
x264 core:155 r2901 7d0ff22
Syntax: x264 [options] -o outfile infile

Infile can be raw (in which case resolution is required),
  or YUV4MPEG (*.y4m),
  or Avisynth if compiled with support (yes).
  or libav* formats if compiled with lavf support (no) or ffms support (no).
Outfile type is selected by filename:
 .264 -> Raw bytestream
 .mkv -> Matroska
 .flv -> Flash Video
 .mp4 -> MP4 if compiled with GPAC or L-SMASH support (no)
Output bit depth: 8/10
.
```

Unless you feel like doing it, I suppose I'll have a go at iterating changes until it works, 

(a) by making a basic ffmpeg library build as a dependency for x264 (or something like that) and checking rdp's site to see if there's any extra configure options to add

(b.1) making a basic gpac library as a dependency for x264 (or something like that) and checking rdp's site to see if there's any extra configure options to add
and/or
(b.2) adding the freshly-updated L-SMASH-Works ( https://github.com/VFR-maniac/L-SMASH-Works or https://github.com/hydra3333/L-SMASH-Works ) (which also has avisynth and vapoursynth, somehow, although I'm not sure what that means in practice) library as a dependency for x264 (or something like that) and checking rdp's site to see if there's any extra configure options to add.

Thanks.

**Comment by hydra3333** [comment]
Um, I must be seeing something wrong, 'x264' already has
```
		'depends_on' : (
			'libffmpeg',
		),
```

**Comment by DeadSix27** [comment]
@hydra3333 should be compiled with ffmpeg, Ill look into it later, but there is no lsmash/gpac, feel free to add a PR for that.
