### ISSUE TITLE
x264 extra build dependencies giving more input/output formats, using libav and LSW

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#58]
ok, following on from https://github.com/DeadSix27/python_cross_compile_script/issues/57

With a few changes, x264.exe can now input files using ffmpeg's libav formats and output .mp4 files directly. eg note the result:

```
x264.exe -h
x264 core:155 r2901 7d0ff22
Syntax: x264 [options] -o outfile infile

Infile can be raw (in which case resolution is required),
  or YUV4MPEG (*.y4m),
  or Avisynth if compiled with support (yes).
  or libav* formats if compiled with lavf support (yes) or ffms support (no).
Outfile type is selected by filename:
 .264 -> Raw bytestream
 .mkv -> Matroska
 .flv -> Flash Video
 .mp4 -> MP4 if compiled with GPAC or L-SMASH support (lsmash)
Output bit depth: 8/10
.

```
Proposed changes:

un-commented-out this since in ffmpeg build options L-SMASH-Works currently depends on it even though it's deprecated, refer issue https://github.com/VFR-maniac/L-SMASH-Works/issues/76
`		'--enable-avresample ' # deprecated. 2018.03.31 except that LSW depends on it, so re-enable it`

Updated 'x264' 
- using your recent change to add PKGCONFIG to 'env_exports'
- added 'liblsw' as a dependency
```
	'x264' : {
		'repo_type' : 'git',
		'url' : 'https://git.videolan.org/git/x264.git',
		'env_exports' : {
			'PKGCONFIG' : 'pkg-config',
		},		
		'configure_options': '--host={target_host} --enable-static --cross-prefix={cross_prefix_bare} --prefix={product_prefix}/x264.installed --enable-strip --bit-depth=all',
		'depends_on' : [
			'libffmpeg', 'liblsw',
		],
		'_info' : { 'version' : 'git (master)', 'fancy_name' : 'x264' },
	},
```
      
added these 2 new dependencies
```
	'libl-smash' : {
		'repo_type' : 'git',
		'url' : 'https://github.com/l-smash/l-smash.git',
		'env_exports' : {
			'PKGCONFIG' : 'pkg-config',
		},	
		'configure_options':
			'--prefix={target_prefix} '
			'--cross-prefix={cross_prefix_bare} '
		,
		'make_options': 'install-lib',
		'_info' : { 'version' : 'git (master)', 'fancy_name' : 'libl-smash' },
	},
	'liblsw' : {
		'repo_type' : 'git',
		'url' : 'https://github.com/VFR-maniac/L-SMASH-Works.git' # vfr_maniac finally updated on 2018.03.31 so use that instead of the fork at 'https://github.com/hydra3333/L-SMASH-Works.git', 
		'source_subfolder' : 'VapourSynth',
		'env_exports' : {
			'PKGCONFIG' : 'pkg-config',
		},	
		'configure_options': 
			'--prefix={target_prefix} '
			'--cross-prefix={cross_prefix_bare} '
			'--target-os=mingw '
		,
		'depends_on' : ['libl-smash'],
		'_info' : { 'version' : 'git (master)', 'fancy_name' : 'liblsw' },
	},
```
Sorry, my fork's not well aligned with your master, hence this instead of a PR.  I reckon I'll need to learn how to rename a fork and then re-fork using the web interface, to be able to submit a PR.

I'll look into using gpac (it's mp4box related IIRC) instead of LSW, since LSW wasn't updated for a lengthy period of time and was broken for 6 months or more.  Anyway, in the meantime there's this.

**Comment by hydra3333** [comment]
Please ignore this. Something's wrong.

_edit: never mind, my fault, I was playing with widl_

**Comment by DeadSix27** [comment]
@hydra3333 I try to avoid avresample since its deprecated, so it would be better to go for gpac but if that is unmaintained or too annoying to build too then just don't bother its not that important since x264 can output mkv anyway its not that hard to remux the mkv or no-container-h264 into mp4 after the fact.

**Comment by hydra3333** [comment]
OK. :) 
my boxes "like" .mp4 ...  will have a go at gpac then.
gpac received an update as recently as 5 days ago so it looks to be maintained.

edit: hmm. many of the .h files in git in gpac/extra_lib/include/ tree are *years* old and the dependency list is longish with some specific versions required.

> 	* freetype2 from version 2.1.4 on.
> 	* SpiderMonkey v1.7 (libjs from mozilla).
> 	* libjpg version 6b
> 	* Libpng version 1.2.33 (older versions should work)
> 	* MAD version 0.15.1b (older versions should work)
> 	* xvid version 1.0 (0.9.0 / .1 / .2 should also work)
> 	* ffmpeg (latest stable API version checked was 17 February 2016 snapshot, you may need to change a few things with current versions)
> 	* libogg 1.1, libvorbis 1.1 and libtheora 1.0 from Xiph.org (newer versions work)
> 	* faad2, version 2.0 or above (2.6.1 working)
> 	* liba52, version 0.7.4
> 	* OpenJPEG, version 1.3
> 	* OpenSVCDecoder, version 1.3

On that basis, I'm giving up on GPAC and will stick with lsw (whilst recognising it uses avresample) in my fork :) until the author of lsw updates it per https://github.com/VFR-maniac/L-SMASH-Works/issues/76

**Comment by hydra3333** [comment]
footnote, 
added this to mp4box configure even though a prior sed takes care of it --target-os=mingw64
and this --enable-pic --enable-depth
