### ISSUE TITLE
including vapoursynth in static build ?

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#61]
https://forum.doom9.org/showthread.php?p=1840703#post1840703

I wonder of this post and those that follow assist in baking in vapoursynth in some way ?
If not directly static, then by running ffmpeg in the same folder as vapoursynth portable ?

**Comment by DeadSix27** [comment]
I do not properly understand you? Do you mind rephrasing?

**Comment by hydra3333** [comment]
Oh, apologies.

I see it seems likely that in the near future ffmpeg may be able to be built with vapoursynth (referenced in the link above) eg with "--enable-vapoursynth".  The link above seems to outline some of the source and build things (but possibly not all, eg zimg and/or avisynth-mt source in the right source subfolders within the vapoursynth source folder) needed to build vapoursynth from Source and python from the DLL in order to result in a static ffmpeg x64 build.

I'm not sure whether your 2 projects (dependencies for mpv build by the looks) 
- vapoursynth_libs : https://github.com/DeadSix27/vapoursynth_mingw_libs.git
- python36_libs : https://github.com/DeadSix27/python_mingw_libs.git

already do those things in the ways ffmpeg may apparently need to build a static .exe, hence I mention and link to it here in case you felt a desire to have a quick look at them and possibly even prep something different for the new ffmpeg-with-vapoursynth static build option :)  

I'm also currently unsure whether those steps will result in a static ffmpeg-with-vapoursynth-built-in or an ffmpeg .exe which has to reside in the same folder as portable vapoursynth/python (it seems not otherwise why build the vapoursynth lib).

Cheers

**Comment by DeadSix27** [comment]
It won't be static the way I make the vapoursynth libs, no. You'll have to have vapoursynth installed.

**Comment by DeadSix27** [comment]
But I will look into it, maybe I can build vapoursynth myself, although I tried that long ago and stopped probably because it's not worth it.

**Comment by hydra3333** [comment]
Ok.  It may be worth it now with the new ffmpeg build option.  
In a week or so I will have more free time to look and learn and tinker, so I may try playing with some things then as well.
Good luck.

**Comment by hydra3333** [comment]
Here's the ffmpeg commit
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/7074a7ccd9a4d4e445252780fd182aa0b3778b79

> avformat: add vapoursynth wrapper
> 
> This can "demux" .vpy files. Autodetection of .vpy scripts is
> intentionally not done, because it would be a major security issue. You
> need to force the format, for example with "-f vapoursynth" for the
> FFmpeg CLI tools.
> 
> Some minor code copied from other LGPL parts of FFmpeg.
> 
> I did not find a good way to test a few of the more obscure VS features,
> like VFR nodes, compat pixel formats, or nodes with dynamic size/format
> changes. These can be easily implemented on demand.

**Comment by DeadSix27** [comment]
I'll play around with it later.

**Comment by DeadSix27** [comment]
Well I got it compiled fine and it's showing no errors when running.. but no video is being outputted..

```
Initialized direct3d renderer.
[vapoursynth @ 0000020595f0d7c0] Opening 'mv_encode.py' for reading
[file @ 0000020595f0d2c0] Setting default whitelist 'file,crypto'
[vapoursynth @ 0000020595f0d7c0] VS format YUV420P8 -> pixfmt yuv420p
[vapoursynth @ 0000020595f0d7c0] Before avformat_find_stream_info() pos: 2955 bytes read:2955 seeks:0 nb_streams:1
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
```

**Comment by DeadSix27** [comment]
oh and I remember why I stopped bothering with building VS:
```
checking for python-3.6... yes
checking for cython3... no
checking for cython... no
configure: error: Cython required but not found
```
I never figured out how to get cython

**Comment by DeadSix27** [comment]
Huh, i was just naive back then, cython just has to be installed on the host e.g on the building system. (e.g by pacman/apt).. testing further

**Comment by DeadSix27** [comment]
Buils fine.. however -> https://github.com/DeadSix27/python_cross_compile_script/issues/61#issuecomment-386777370

**Comment by DeadSix27** [comment]
ffmpeg will just use the vapoursynth pc files it creates which define:
`Libs.private: -L/xc/gcc7/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib -lpython36`
Which works just fine, you do not even need to add -lstdc++ (probably because another library already does this, I added it manually, made no difference so meh)

**Comment by hydra3333** [comment]
Ah.  Thanks !

**Comment by hydra3333** [comment]
A thought. 

VS depends on https://github.com/sekrit-twc/zimg which we build elsewhere, so OK.
In order for VS scripts to import/use avisynth bits, it also depends on https://github.com/pinterf/AviSynthPlus/tree/MT ... would it be wise to include that too and "--disable-avisynth" so that no conflicts occur  ?

**Comment by DeadSix27** [comment]
The issue is I still have to give it all the dll's.. as if it's still not linked statically, despite me compiling it static.. which is strange.
E.g building vs with: --enable-static --disable-shared
building ffmpeg with --enable-vapoursynth
= results in ffmpeg demanding .pyd and VScript.dll/VapourSynth.dll

I did test adding the -static ldflag, but that made no difference.

**Comment by hydra3333** [comment]
OK.. I can't see your configures so just a dumb question, I assume you've seen the flags in this ?
https://forum.doom9.org/showthread.php?p=1840703#post1840703

**Comment by DeadSix27** [comment]
@hydra3333 Yes see edited post above.

**Comment by hydra3333** [comment]
Would it be possible to see your ffmpeg commandline and .vpy script ?  So that I can duplicate it as reasonably close as possible in my tinkering.

**Comment by DeadSix27** [comment]
@hydra3333 --enable-vapoursynth and optionally: --extra-ldflags="-static"
Rest is same as master on this repo

However I uninstalled the vapoursynth libs I used to use and ran `-d vapoursynth` to build of source, rather than making import libs via gendef

**Comment by hydra3333** [comment]
Thanks.  I meant the ffmpeg commandline and .vpy you used when it failed to give you a video output.

**Comment by DeadSix27** [comment]
@hydra3333 Oh, `ffplay -f vapoursynth file.py` `ffmpeg -f vapoursynth -i test.py out.mkv`

**Comment by hydra3333** [comment]
Not sure if this helps ...

jb-alvarado/media-autobuild_suite
"ffmpeg: add vapoursynth support"
https://github.com/jb-alvarado/media-autobuild_suite/commit/1e6181a698816701b4a291dc524c50262ee806ce

**Comment by hydra3333** [comment]
Sorry, I couldn't get it to build vanilla ffmpeg with the script as it stood.  
A guess could be a missing ffmpeg dependency on vapoursynth which had been previously built somehow and which thus exists in /lib etc ?
I could be doing something wrong though.

**Comment by hydra3333** [comment]
edit: snip ... unneeded rubbish.

**Comment by DeadSix27** [comment]
You do realize i do this already right?:
https://github.com/DeadSix27/vapoursynth_mingw_libs

**Comment by DeadSix27** [comment]
PS: I skipped over w hat u wrote and pretty much everyhting you do in your code, I do in `vapoursynth_mingw_libs` repository. which is being run by:
'vapoursynth_libs' so I don't know why you went through the effort of recreating it inside the compilescript..

**Comment by hydra3333** [comment]
OK, fair enough.  
I did see it and admired it.  
It seems to do a tad more than JB's in the .pc  (private libs) which I'm betting is required.
It is a dependency for mpv. 
Cheers !

**Comment by DeadSix27** [comment]
Sorry that you went through and made all that...  were they any additions or changes to how I do it in the separate script I made?

**Comment by hydra3333** [comment]
Not an issue for me since I'm still fiddling with it and learning atm so errors on my part and my partly-working code are acceptable to me as a part of that process.  
A mate once told me circa 1980 (in relation to motor bike trail riding) "if you don't fall off then you aren't trying hard enough" and that works for me as an approach :)

If it if works for you then i'd suggest no changes needed.
Nice tools !

**Comment by pat357** [comment]
@DeadSix27 
How did you compile the static build **vapoursynth.a** and **vsscript.a** in **ffmpeg ?**
Did you check if the variable **VS_CORE_EXPORTS** does contain anything ?
Did you change the **vapoursynh.pc/vsscript.pc** files to reflect that the above a **static** now, or how did you do it ?
Make sure that ffmpeg can not find the .dll files from vapoursynth or vsscript.
If you installed VS , there is a .dll in your /system32 under the /windows dir. Rename it.

The Python part is relative easy, just make sure it loads delayed.

If the static vsscript and vscore are properly linked to ffmpeg, the resultiing ffmpeg.exe will not have any dependencies to vsscript. you can check this with dependency walker or similar.
