### ISSUE TITLE
A few potential issues

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#71]
in `'opencl_headers' : {` per  https://github.com/KhronosGroup/OpenCL-Headers

the headers seem to be in a subfolder CL/*.h rather than opencl22/CL/*.h ?

**Comment by hydra3333** [comment]
A thought,
```
	'p11-kit' : {
		'repo_type' : 'archive',
		'needs_make_install' : False,
		'url' : 'hhttps://github.com/p11-glue/p11-kit/releases/download/0.23.9/p11-kit-0.23.9.tar.gz',

```
may have one too many "h" in https

**Comment by hydra3333** [comment]
Just a note, I had trouble building one of the dependencies with this newest version of the compiler.  I forget which dependency, but it was obvious enough when it occurred.  
Official gcc 8.1.0 release worked though.
This was under latest Ubuntu in a vm.
Cheers

PS, thank you for your ongoing great work !

**Comment by DeadSix27** [comment]
@hydra3333 A lot of the libs, e.g p11, I do not actively use, so I never update them and I can currently build fine, but I updated the gcc snapshot, maybe this newer one works fine now for you?
I am a little busy right now hence the slow updates

**Comment by hydra3333** [comment]
@DeadSix27 cool.
