### ISSUE TITLE
a method to build ffmpeg with vapourynth

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#84]
I wonder, have you seen this ?
http://forum.doom9.org/showthread.php?p=1875818#post1875818
https://github.com/qyot27/mpv/blob/extra-new/DOCS/crosscompile-mingw-tedious.txt#L4396

**Comment by DeadSix27** [comment]
What about it?
Knew everything he mentioned in that post and I tried to cross-compile VS before.. but I never got it to work with Python.. he seems to not get it to work either, hence why he uses "--disable-python-module".

Which I do not want to do if possible.

**Comment by DeadSix27** [comment]
Maybe something changed.. if I find the time I'll look at it again, but the gendef method seems fine? Not the prettiest but the result works fine. (As long VS keeps providing binaries, I don't see why they wouldn't)

**Comment by hydra3333** [comment]
OK, no worries, just linking to something you may potentially not have seen before.
