### ISSUE TITLE
srt build options have changed ?

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#85]
looks like -DUSE_GNUTLS=1 is superseded by -DUSE_ENCLIB=gnutls

however it still fails to build for me, failed to locate some .h file.

**Comment by hydra3333** [comment]
ah, there's a pending commit over there to fix it.
https://github.com/Haivision/srt/pull/779

**Comment by DeadSix27** [comment]
fixed via https://github.com/DeadSix27/python_cross_compile_script/commit/18ffe346814f415540d7e4491703be877ffc3622

**Comment by hydra3333** [comment]
thank you.
i see gnutls still works now.
i guess i'll need to look into the reason for change of choice from gnutls to libressl :)

**Comment by DeadSix27** [comment]
i changed back.
https://github.com/DeadSix27/python_cross_compile_script/commit/304ec6db34a705ba21f791e15ca7eefbdefaf814
