### ISSUE TITLE
latest GIT mingw64 doesn't build anymore, they broke it upstream 

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#88]
latest GIT mingw64 doesn't build anymore, they broke it upstream :(
it seems that if you add the "'checkout' : 'tags/v6.0.0', " line to the toolchain build script then it builds.

```
SOURCES['mingw-w64'] = {
	'type' : 'git',
	'url' : 'https://git.code.sf.net/p/mingw-w64/mingw-w64', # https://sourceforge.net/p/mingw-w64/mingw-w64/commit_browser https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/ # mirror: https://github.com/mirror/mingw-w64.git but that seems suprisingly out of date sometimes.
	'checkout' : 'tags/v6.0.0', # cb090affef8ebcd8c13ffc271b4500dea3b52f33
	'run_after_patches' : [
		( 'autoreconf -fiv', ),
		( 'mingw-w64-crt'  , 'autoreconf -fiv' ),
	],
	'builds' : [
		'mingw-w64-crt',
		'mingw-w64-headers',
		'mingw-w64-gendef',
		'mingw-w64-winpthreads',
		#'mingw-w64-widl', #2018.08.16 # Still won't compile, 'mingw-w64-tools/widl/src/widl.c:172:28: error: array type has incomplete element type ‘struct option’'
	]
}
```

**Comment by DeadSix27** [comment]
works fine for me now?

**Comment by DeadSix27** [comment]
Nvm, they added this: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/b4a4588bd59740b0d4001f96758f10cbf560da86/
Revert to 0a1d495478d8ed1a94fc77b9dbb428b7e0372588 for now

**Comment by hydra3333** [comment]
👍

**Comment by DeadSix27** [comment]
It works with this work-around:
<https://github.com/DeadSix27/python_cross_compile_script/commit/d7c42d04307942bb7f3c3266bee1f2e8795fa8bd>
But I would need to ask someone with more c++/gcc knowledge to tell me if this is even the right way, I'm not sure.

**Comment by hydra3333** [comment]
hydra lowers eyes and mumbles "IDK".

**Comment by DeadSix27** [comment]
I'll close this until someone complains

**Comment by hydra3333** [comment]
It seems 
`'checkout' : 'tags/v7.0.0'`
works ... 

for libspeex, if using 
`-fstack-protector-all -D_FORTIFY_SOURCE=2`
then it seems we need to add
`-D_FORTIFY_VA_ARG=0`
to an export of cflags.

As an aside, it appears that the ffmpeg stuff and dependencies at least builds (if not runs - untested as yet) with
`-fstack-protector-all -D_FORTIFY_SOURCE=2`
Just tinkering :)

**Comment by hydra3333** [comment]
Uh, please ignore that.  It stopped building :(
