### ISSUE TITLE
gmp-6.1.2 needs a patch to cross compile

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#90]
hello.
what do you make of this ?
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/402
worth implementing ?

**Comment by DeadSix27** [comment]
As far as I can tell from short look over of his message:

He fixes the binary (.exe) building with his patch which in turn allows the gmp-build to generate tables and whatnot? I haven't looked into what those are good for yet.. but here's things to consider:

1) I don't need/want wine installed for this project, but we need it for this to even work.
2) All we need is the gmp library, not sure if the patch and the extra build steps it does, adds anything worth to us to the library, maybe more functions? So far I haven't run into anything that's missing, but I'm very far from using ffmpeg to its extent.. maybe some obscure filter needs it.

**Comment by hydra3333** [comment]
:) sounds OK by me.  
the current .exe currently works for my limited use cases as well.
