### ISSUE TITLE
mingw32 vs mingw64

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#95]
Hello.  Thank you for your ongoing great work !

A newbie dummy's question:
"mingw32" seems to be hard-coded through cross_compiler.py, ffmpeg variable, the toolchain builder etc
... so, for example in ffmpeg_base_config, should
`'--target-os=mingw32 '`
be 
`'--target-os=mingw64 ' # ??? to enable mingw64 for 64-bit target ??? {bit_name3} won't yield "mingw32" so hard-code `?

I am guessing I mis-understand the meaning of --target-os etc

**Comment by DeadSix27** [comment]
**In general:**
64bit might be hard coded in some places as after a while I stopped caring about 32bit and stopped supporting it.

**About that line specifically:**
mingw32 in this case is just the platform or w/e, ffmpeg uses that as the OS to compile for.
The actual 32/64bit value is stored in:
`--arch={bit_name2}`
bit_name2 will return x86_64 (64bit) and x86 (32bit), but again 32bit is not supported in any way.


Does this explain it?

**Comment by hydra3333** [comment]
OK, 64 bit seems prudent as it is a current OS etc so that's good.

OK, 
ffmpeg's "--target-os" is the target platform (operating system, I guess) to compile for, not the bits the o/s is built for, whereas 
ffmpeg's "--arch" is the bits the target o/s is built for

I wonder what happens if we replace 
`--target-os=mingw32 `
with
`--target-os=mingw64`
wherever it appears in the scripts ?

**Comment by DeadSix27** [comment]
> I wonder what happens if we replace

Nothing different.

https://github.com/FFmpeg/FFmpeg/blob/master/configure#L5311

**Comment by hydra3333** [comment]
Ah ha !
