### ISSUE TITLE
Vulkan-Loader: Patch does not apply to current master branch

### ISSUE THREAD

**Issue by 1480c1** [DeadSix27/python_cross_compile_script#98]
`ENABLE_STATIC_LOADER` was removed in https://github.com/KhronosGroup/Vulkan-Loader/pull/260

loader/CMakeLists.txt doesn't apply anymore

**Comment by DeadSix27** [comment]
shinshiro seems to have just patched the static loader back in, probably will just use his patch. Seems fine.
I do wonder if in the future we can use build it shared

EDIT: I have not looked that far into it yet, not sure if this is something mpv/libplacebo has to add/support or if its fully on our end.

**Comment by DeadSix27** [comment]
I did end up actually switching to shared build, we already do that with opencl too so it's fine.

You just need the driver installed.
